### ISSUE TITLE
run.sh should not download clinvar and other data to current directory

### ISSUE THREAD

**Issue by mvelinder** [dillonl/VarBayes#8]
We probably don't want them to generate a `data/` folder with clinvar and other annotations in it for every run they do, could we not just have it download to the bAyesCMG install dir and all future runs reference it at that location?

**Comment by dillonl** [comment]
This is now done the way you suggested. clinvar data is now downloaded to the bAyesCMG install dir.

**Comment by mvelinder** [comment]
Still getting a data/ dir in the dir I'm running in

```
(base) [u0691312@redwood5:A569]$ ll data/
total 1075124
drwxrws--x+ 2 u0691312 marth       4096 Apr 20 11:40 ./
drwxrws--x+ 3 u0691312 marth       4096 Apr 20 11:40 ../
-rw-rw----+ 1 u0691312 marth   26624885 Apr 20 11:41 clinvar.grc37.vcf.gz
-rw-rw----+ 1 u0691312 marth     285247 Apr 20 11:41 clinvar.grc37.vcf.gz.tbi
-rw-rw----+ 1 u0691312 marth 1073999449 Apr 20 11:54 clinvar.grc37.vep.vcf
```

**Comment by mvelinder** [comment]
Working now
